### PR TITLE
Fix a typo in en_us.json

### PR DESCRIPTION
**Pull request by TheBunnyMan123**
This PR fixes a typo I made that was merged with #214, where I forgot to add a space to a sentence

### CODE REVIEW

**Comment by UnlikePaladin** [comment]
lol that's so me 💀

**Comment by ElectricDaFearox** [comment]
HE'S JUST LIKE ME FR

**Comment by TheBunnyMan123** [comment]
I would have missed it too. Proof: I missed it

**Comment by PoolloverNathan** [comment]
more and more layers...  
image

**Pull request merged**
