### PR TITLE
create sync workflow

### PR DESCRIPTION
**Pull request by repository**
syncs strings from `en_us.json` to assets repo

### CODE REVIEW

**Comment by Covkie** [comment]
shouldn't the branch be 'HEAD' instead of '1.20' to prevent future changes needing to be made when the head branch changes

**Comment by KitCat962** [comment]
1.20 is the head/default/main branch

**Comment by repository** [comment]
> shouldn't the branch be 'HEAD' instead of '1.20' to prevent future changes needing to be made when the head branch changes

that doesn't work for specifying branches in the push event

**Comment by Covkie** [comment]
> that doesn't work for specifying branches in the push event

ah okay I didn't know that.

**Pull request merged**
