### PR TITLE
Update dependencies furtherly, Apply other required changes.

### PR DESCRIPTION
**Pull request by Kichura**
**Dependencies that will be updated:**

Machete = 1.1.4 -> 2.0.1,
Shadow = 7.1.2 -> 8.1.1,
Pack format in Forge = 13 -> 15,
Forge itself = 1.20.1-47.1.28 -> 1.20.1-47.1.37,
Mod Menu = 7.1.0 -> 7.2.1,
Fabric API = 0.85.0 -> 0.86.0.

**Other changes:**

1. The `./gradlew mergeJars` command doesn't need a multi-run script in place as there is only one for it,
2. Minor adjustments to gradle configurations have been made to look better,
3. Originally this PR was going to tell gradle to try and sync latest fabric loader to the main JSON but since that won't work, The latest version will be manually added instead with an `>=` to indicate that newer versions are accepted,
4. Now filters extra unwanted crap from GitHub itself using the gitignore file,
5. Machete has been removed as it is no longer a required library,
6. The LuaJ library sources have been corrected to the new sources,
7. The figura IP has been changed to make mod work properly again. *(Temporarily?)*

### CODE REVIEW

**Comment by UnlikePaladin** [comment]
Probably needs testing, dependencies blindly isn't a good idea, they could break stuff, we're also removing machete, it goes unused

**Comment by Kichura** [comment]
> Probably needs testing, dependencies blindly isn't a good idea, they could break stuff, we're also removing machete, it goes unused

I have tested this prior and it's working without issues, will remove unused package and see how it goes.

**Comment by Kichura** [comment]
No game breaking issues found although only problem i ran into *(unsure if it already was like it prior)*: the cloud server seems to be spitting out an internal error but aside from that, models are working.

**Comment by skyrina** [comment]
> the cloud server seems to be spitting out an internal error

could you clarify what this means?

**Comment by Kichura** [comment]
> > the cloud server seems to be spitting out an internal error
> 
> could you clarify what this means?

This is what it's telling:
figura

**Comment by skyrina** [comment]
that's weird.. i've never seen that. any errors in logs?

**Comment by Amalyris** [comment]
likely on cloud.figuramc.org, change backend url to figura.moonlight-devs.org 

actually reading the previous context that's weird,for other people the issue was caused by wrong url, doesnt seem to be the case here though , try to see anyways?

**Comment by Kichura** [comment]
> likely on cloud.figuramc.org, change backend url to figura.moonlight-devs.org
>
> actually reading the previous context that's weird,for other people the issue was caused by wrong url, doesnt seem to be > the case here though , try to see anyways?

Will try it.

**Comment by Kichura** [comment]
URL is working properly in figura.

**Comment by UnlikePaladin** [comment]
Yeah the backend is moving to that other new IP eventually, just not for the moment

**Comment by Kichura** [comment]
> Yeah the backend is moving to that other new IP eventually, just not for the moment

If it needs to be undoed at anytime, push an comment here and i can do it.

**Comment by UnlikePaladin** [comment]
has merge conflicts, plz fix

**Comment by Kichura** [comment]
> has merge conflicts, plz fix

Sorry for my late response but i was busy doing IRL things earlier, hence why i could not look into my PR but thanks for assisting with getting this merged.

**Pull request merged**
