### PR TITLE
Change to PolyForm Noncommercial License 1.0.0

### PR DESCRIPTION
**Pull request by UnlikePaladin**
Figura is switching to the PolyForm Noncommercial License to prevent others from using it for monetary purposes as well as better legal protection.

### CODE REVIEW

**Comment by soup587** [comment]
:+1:

**Review by PoolloverNathan — APPROVED** [review]

**Review by lexize — APPROVED** [review]
Nyaboom (yes)

**Comment by GrandpaScout** [comment]
This comment displays my approval of this change.

**Review by Riftlight — APPROVED** [review]

**Review by skyrina — APPROVED** [review]

**Review by Kichura — APPROVED** [review]

**Review by aprilkenopsia — APPROVED** [review]
Yep thats a license for sure

**Review by playgamesgo — APPROVED** [review]

**Comment by JimmyHelp** [comment]
👍

**Review by TooManyLimits — APPROVED** [review]
I approve of changing the license.

**Review by KitCat962 — APPROVED** [review]
Approved!
knuckles-approved

**Review by ToastTextures — APPROVED** [review]
Yuh

**Comment by ChloeSpacedOut** [comment]
👍

**Comment by auriafoxgirl** [comment]
Meow (I approve)

**Review by auriafoxgirl — APPROVED** [review]

**Review by ChloeSpacedOut — APPROVED** [review]
👍

**Comment by 4P5** [comment]
lgtm

**Comment by envicious** [comment]
lgtm, approved
[a near perfect license](https://youtu.be/JkZP11hv6D8)

**Comment by Manuel-3** [comment]
approved

**Review by gloomsys — APPROVED** [review]
this is yes :3

**Comment by omoflop** [comment]
👍

**Review by omoflop — APPROVED** [review]
Looks good

**Review by TotalTakeover — APPROVED** [review]
Looks good to me!

**Review by PoolloverNathan — APPROVED** [review]
[get demonstrated](https://github.com/user-attachments/assets/e63da0ce-d474-44bd-838e-8b1c60a6e3a3)

**Review by envicious — APPROVED** [review]
Thumbs up

**Review by purpledeni — APPROVED** [review]
goober aproved

**Review by soup587 — APPROVED** [review]
oh i can review apparently

**Review by TJT01 — APPROVED** [review]
:thumbsup:

**Review by TJT01 — APPROVED** [review]
:thumbsup:

**Comment by TJT01** [comment]
double post wth

**Review by Covkie — APPROVED** [review]

**Review by Amalyris — APPROVED** [review]

**Review by HastagGuigui — APPROVED** [review]
i am horrible at legalese but if i understand it correctly yeah that seems good

**Comment by alekso56** [comment]
Approved, but you should probably specify the License owner, else attribute it to this github repo.

**Comment by superpowers04** [comment]
I approve of the license changes :3 (github isn't letting me approve the PR directly)

**Review by KitCat962 — APPROVED** [review]
Approved part 2

**Review by aprilkenopsia — APPROVED** [review]
3dgifmaker29750

**Review by PoolloverNathan — APPROVED** [review]

**Review by lexize — APPROVED** [review]
At the beginning, there was a nyaboom, at the end, there was a nyaboom,,,,

**Review by playgamesgo — APPROVED** [review]

**Comment by Manuel-3** [comment]
approved electric boogaloo

**Review by envicious — APPROVED** [review]
Here we go again

**Review by HastagGuigui — APPROVED** [review]
yep yep seems good to me

github sure is a platform ever

**Review by ToastTextures — APPROVED** [review]
Honk shoo honk shoo mimimimimi
Let me sleep smh

And never bring back the random green pixels

**Review by purpledeni — APPROVED** [review]
https://vxtwitter.com/MulhollandL0ver/status/1847042766041166123.mp4
https://tenor.com/view/akuma-sf6-gif-1682706543702075673

**Review by auriafoxgirl — APPROVED** [review]
uhh meow?

**Review by TJT01 — APPROVED** [review]
👍🏻

**Comment by UnlikePaladin** [comment]
this new license fits the spirit of the project better as it does allow forks and stuff, just not people to use it to make profit, therefore the change and request for reviews again

**Review by 4P5 — APPROVED** [review]
still lgtm

**Review by soup587 — APPROVED** [review]
https://cdn.discordapp.com/emojis/1098005568741970000.webp?size=96

**Comment by alekso56** [comment]
Approved, same comment as before.

**Review by JimmyHelp — APPROVED** [review]

**Review by Riftlight — APPROVED** [review]
approved 2 electric boogaloo

**Comment by GrandpaScout** [comment]
This is yet another comment stating my approval of yet another change

**Review by Kichura — APPROVED** [review]

**Review by TotalTakeover — APPROVED** [review]
This is a certified hood classic

**Comment by superpowers04** [comment]
i think i need to approve again so i do

**Review by TooManyLimits — APPROVED** [review]
I agree with the change to the PolyForm Noncommercial License.

**Review by omoflop — APPROVED** [review]
:+1:

**Review by skyrina — APPROVED** [review]

**Review by gloomsys — APPROVED** [review]
yurr

**Review by TheBunnyMan123 — APPROVED** [review]
pretty sure I need to approve this as well, so approved.

**Review by penguinencounter — APPROVED** [review]
I technically haven't written any of the code in the repo yet, but I approve of the change to PolyForm Noncommercial and relicensing of all my current contributions etc etc

also @UnlikePaladin you should change the issue description to have the right license name

**Review by ChloeSpacedOut — APPROVED** [review]
👍

**Review by Covkie — APPROVED** [review]

**Comment by Covkie** [comment]
@UnlikePaladin bwaa

**Review by Amalyris — APPROVED** [review]

**Comment by UnlikePaladin** [comment]
Will merge now :)

**Pull request merged**
